baseURL = 'https://nandaja.space/'
languageCode = 'en-us'
title = 'Nandaja'

favicon = "r"

theme = "hugo-bearblog"

copyright = "Nandaja Varma" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set


# Main menu which appears below site header.
[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "light" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = true # default

  # Home page settings
  description = "Hi! I am Nandaja. Your (not so) friendly neighborhood programmer. Living in Milan üáÆüáπ, originally from Kerala üáÆüá≥. <a href=https://www.gitpod.io/>Gitpodder üçä </a>"
  mainSection = "posts" # your main section
  mainSectionTitle = "Blog"
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/nandajavarma" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default


  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/nandajavarma"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/nandajavarma/"
  [[params.social]]
    name = "email"
    link = "nandaja.varma@gmail.com"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/nandajavarma"
